### ISSUE TITLE
Tag recordings upload errors

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#105]
Tag recordings are not going through for project 96, the error message is that there are no recordings found in the files, but I'm able to open them in audacity and see the bursts - they've been deployed now so hopefully registrations are useable
 - project 167 is having similar issues with the error:
Error: Error in createRecvTagDB(projectID, dateBin): No tags found for project 167 with dateBin in 2017-3
- also projects 95, 109, 38, and 138

**Comment by jbrzusto** [comment]
closing this in deference to MotusWTS/Motus-TO-DO#40
