### ISSUE TITLE
Project 145 blank hourly plot data

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#112]
Project 145:
I'm not sure if this is a user issue or a bug in the system.  But a recent upload of Michigan KIWA data shows that all receivers had intermittent GPS fixes, no antennas, and no detections - BUT there are tagIDs listed on the plots despite no detections.  So are there detections that aren't showing up for some reason?  Or were all of these receivers truly running for months with no antennas connected?

All the data is in https://sensorgnome.org/download/0/ for the following receivers:
Receiver Lotek-D000452:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000453:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000454:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000455:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000456:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000457:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000458:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000459:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000460:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000461:  the .DTA files have no new data, so the tag finder will not be run
Receiver Lotek-D000462:  the .DTA files have no new data, so the tag finder will not be run

Backstory: Nathan Wands uploaded the data August 14 but since the receivers were entered with an incorrectly formatted serial number (entered as SRX-800s when they should have been SRX-DLs), they were placed in project 0.  I downloaded and re-uploaded the data after fixing the serial numbers online in the hopes it would be loaded to project 145 hourly plots. That's why I got the above output after re-upload, I'm not sure how that might affect the plots, but that's all the info I know.

Project 74:
Some plots have a warning printed on them, "error using packet 1 only 0's may be mixed with negative subscripts"
eg. https://sensorgnome.org/download/74/Lotek-160-2016_CTRiver_Wantastiquet_hourly_tags.png

**Comment by jbrzusto** [comment]
There were a bunch of bugs affecting this, which are now fixed on the new server.
I'll backport changes to the old server and rerun those receivers so the plots are corrected.

**Comment by jbrzusto** [comment]
see new plots here:

  https://sgdata.motus.org/download/145
