### ISSUE TITLE
empty tag registrations

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#117]
Stephanie Feign tried uploading some tag detections, job 599833.  All the 200 series she uploaded were fine, but tags 45-94 failed because "No tags detected in file tag045.wav".  I looked at the files, the recordings show very very small blips for each burst, but they looked just as small for the 200 series which registered fine - does she need to re-record?

**Comment by jbrzusto** [comment]
Just to summarize, tags 45-94 appear to be using the older (7.5, 5, 5,
5) ms pulse length pattern that uses more than double the power (so
halves the battery life) of the usual (2.5, 2.5, 2.5, 2.5) ms pattern,
and is also much less reliably detected by SG receivers (it's fine
with Lotek receivers).  

The tags from 212 to 241 were programmed to use the usual pattern,
which registered fine.
