### ISSUE TITLE
Empty files in uploaded data

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#118]
Job status job 613878 says all files were empty, but Junior Tremblay says it should contain all 2017 data so he was expecting detections.  He had tried to upload the same data but got error messages in job 613533.

If they truly are empty, then it's possible there's an issue with that receiver that they'll need to deal with

**Comment by jbrzusto** [comment]
Data now seem complete:

https://sgdata.motus.org/status?serno=SG-5113BBBK3157
