### ISSUE TITLE
tagme() rejecting login

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#134]
I haven't been able to login through the motus R package to access the tagme() function since sometime on Friday - I get the error "The motus data server rejected your login credentials"

**Comment by zcrysler** [comment]
Strange - it's working for me now too.  I had tried it a bunch of times earlier with no success so whatever the reason restarting the data server seemed to have solved the problem!

**Comment by jbrzusto** [comment]
reopening:  the problem is due to server connections lapsing.
the `authenticate_user` API was not properly checking for this, because iit doesn't go through
`validate_request()`

**Comment by jbrzusto** [comment]
closing in deference to jbrzusto/motusServer#281
