### ISSUE TITLE
Priority data: missing data from processed upload 110484

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#150]
Priority if possible - an honours student needs to present data in the next 12 days:

Data was uploaded for SG-4812BB000333 receiverID 1427, project 78.  The processing page says it was processed ok (jobID 110484), but the plot doesn't have any 2017 data: https://sgdata.motus.org/download/78/SG-4812BB000333-2015_HamiltonWHIM_Lameque%201%20-%20Petit%20Shippagan_hourly_tags.pdf

Their .motus files don't contain data for this receiver for 2017, I downloaded the receiver file using tagme() and only got data up to 2015-08-04

**Comment by zcrysler** [comment]
There are a few uploads that didn't go through for project 78 that the honours student needs for her results

**Comment by jbrzusto** [comment]
These data are now available [here](https://sgdata.motus.org/status?jobID=124775) and
via the data server (motusClient package).

The receiver was re-run after fixing boot numbers using the (now working) `ensureMonoBN()`
function.

**Comment by zcrysler** [comment]
Thanks John,
Can the other error uploads in project 78 be rerun as well?

Wilson's point SG-2712BB000151 jobID 110488
Pokesuide SG-2712BB000003 jobID 110486
Johnson's Mills 2712BB000055 jobID 110476

**Comment by jbrzusto** [comment]
These 3 are now done too.
