### ISSUE TITLE
realtime sensorgnome status page down

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#154]
There are no receivers listed here: https://sensorgnome.org/Internal_pages/Realtime_Sensorgnome_Status

and in particular these receivers don't appear to be streaming:
SG-5C00RPI33593
and https://github.com/jbrzusto/TO_DO/issues/135

**Comment by jbrzusto** [comment]
- server down:  metadata cache was obliterated by 1.0 motus API no longer functioning, apparently.
I've made a static copy of the cache from the new server.

- receivers not streaminig: still needs to be dealt with, but is #135
