### ISSUE TITLE
proj19 2016 data not transferred to new server

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#158]
I uploaded data for project 19 2016 Jamaica receivers, but it wasn't processed because the data already existed, but data hasn't been transferred to the new server so aren't available for users:

jobID 127426, SG-0816BBBK0521
jobID 127432, SG-0816BBBK0192
jobID 127438, SG-0816BBBK08C1
jobID 127446, SG-0816BBBK064C
jobID 127447, SG-0816BBBK039D

**Comment by parzudak** [comment]
2016 data from proj 19 also missing for:

SG-3114BBBK2156
SG-3114BBBK2336
SG-3114BBBK2178 (2016 and some 2017)
SG-3114BBBK2277

**Comment by jbrzusto** [comment]
rerunning all of these receivers now.
