### ISSUE TITLE
SG-0815BBBK0176 processing incomplete?

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#164]
Data uploaded for this receiver JobID 125269, there should be data for 2018-01-17 to 2018-01-21, everything indicates it was processed correctly, but no hourly plot was made and I can't find any data using tagme().  Is this because there was no data in those files, or due to a processing error?  project 174

**Comment by jbrzusto** [comment]
Not sure why the plots weren't generated.  I've re-exported the data and regenerated the plots:

   https://sgdata.motus.org/status?jobID=130702

**Comment by zcrysler** [comment]
Perfect - and available with tagme() too
