### ISSUE TITLE
project 3 upload processing errors

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#166]
From Junior Tremblay:

1.
Processing Summary:
File uploaded: 234_2018-02-08T11-47-45.317_SGdata5113BBBK1655.7z
Will run tag finder on 1 receiver boot sessions
Error: Error in seq.int(0, to0 - from, by): 'to' must be a finite number

2.
Processing Summary:
File uploaded: 234_2018-02-08T11-40-55.364_SGdata5113BBBK3118c.7z
Will run tag finder on 1 receiver boot sessions
Error: Error in seq.int(0, to0 - from, by): 'to' must be a finite number

3. 
Processing Summary:
File uploaded: 234_2018-02-08T12-42-04.186_SGdata5113BBBK3118a7z.7z
Error: Error in rsqlite_send_query(conn@ptr, statement): database is locked

Can you tell me what are the impact of these errors and if I or you can do something to correct them?

**Comment by jbrzusto** [comment]
### 234_2018-02-08T11-47-45.317_SGdata5113BBBK1655.7z ###
This is [job 130128](https://sgdata.motus.org/status?jobID=130128)
The subjob which failed is `plotData`, which generates summary plots.  This means any data
from that processing session will still be available through the motus R package.
However, this is obviously a bug  in server code too: jbrzusto/motusServer#353

### 234_2018-02-08T11-40-55.364_SGdata5113BBBK3118c.7z ###
Same bug as above.

### 234_2018-02-08T12-42-04.186_SGdata5113BBBK3118a7z.7z ###
This is another bug (jbrzusto/motusServer#341).  It is exposed when two `processServers` both try to work on data for the same receiver, and is triggered by uploading separate files for the same receiver.  
(If the files for SG-5113BBBK3118 had been combined into a single archive, this bug would not have been triggered).  Each file uploaded in a batch is potentially handled by a different `processServer`.
I will re-run this receiver.

**Comment by jbrzusto** [comment]
Large numbers of files didn't make it from the old server to the new server for this receiver.
Moving these before re-running...

**Comment by jbrzusto** [comment]
Rerun status is here:  https://sgdata.motus.org/status?jobID=132872

**Comment by zcrysler** [comment]
Thanks!
