### ISSUE TITLE
proj 159/15 data not uploading properly

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#170]
userID 234 uploaded a number of receivers to projects 159 and 15 on Feb 12, he got to the page where he selected which project to assign them to, and it seemed to save fine, but they never showed up anywhere.  If they aren't in the Manage Files page of the upload site - does that mean they never made it to the server, or so there somewhere they could be stuck in limbo?

**Comment by jbrzusto** [comment]
My fault:  in fixing jbrzusto/motusServer#346, I missed a spot in the projectSend code that needs to know
where the metadata DB resides.

### Fix ###
- [ ]  change path to sqlite meta DB in ProjectSend

**Comment by zcrysler** [comment]
+ [ ]  inform users they need to re-select projects and submit the files (the files don't need to be
uploaded again - they should appear in each user's Manage Files page now)
users are: 104, 234, 248, 2340, 2418

Done
