### ISSUE TITLE
Failed tag registration

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#171]
jobID 134700 was a tag registration uploaded through the motus server https://sandbox.motus.org/data/project/sgJobs?projectID=1, it didn't show any errors and the confirmation email said it had been processed but 0 tags registered - is this an issue with the recording or the processing?

**Comment by jbrzusto** [comment]
I can't login to the link above, but the view [here](https://sgdata.motus.org/status?jobID=134700) indicates the tag failed to register.  I seem to have [mistakenly](https://github.com/jbrzusto/motusServer/issues/357) dropped the detailed error messages for why tag registrations have failed.

**Comment by zcrysler** [comment]
Ok, so it's likely a recording issue?

**Comment by jbrzusto** [comment]
Not sure yet - I will re-run the job once I've put the messages back.

**Comment by jbrzusto** [comment]
A retry shows an error is being returned by the motus.org server, so I'm filing an issue [there](https://github.com/MotusDev/MotusAPI/issues/4).

**Comment by jbrzusto** [comment]
The error returned by motus.org is now included in the log, so I'm closing this issue.
