### ISSUE TITLE
proj 31 failed processing

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#182]
Receiver Lotek-358 has had a DTA file with data up to 06/17/17 uploaded but there was an error with job 124573, can you rerun this receiver please?

**Comment by jbrzusto** [comment]
[Done](https://sgdata.motus.org/status?jobID=166552)
And thanks for pointing it out, as it is only [one of many](https://github.com/jbrzusto/motusServer/issues/306) which I should have dealt with months ago!
