### ISSUE TITLE
Error unpackArchive proj 6

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#185]
Job ID 168499 has an error for unpackArchive, but the data all seems to have been processed - is this an issue that needs addressing or is everything fine?

**Comment by jbrzusto** [comment]
ref: https://sgdata.motus.org/status?jobID=168499

This error doesn't cause any real problems, but does pollute the job log.
It looks like this is an archive generated by Dropbox, as symptoms are identical to this

   https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname

I will follow the suggestion there to exclude the spurious "/" entry from the archive.
