### ISSUE TITLE
No files extracted jobID 168802

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#186]
https://sgdata.motus.org/status?jobID=168802

I got a confirmation email that processing was done and there are no errors, but data isn't available and there's a line in the job status "No files extracted".  The file I uploaded had date folders for 2017-11-28 to 2018-02-24

Data was downloaded through WeTransfer if that has an effect like Drop Box

**Comment by pmorrill** [comment]
John: this file was uploaded to Motus (the shared drive) using our new 'chunked' file upload script. Can you verify that the file itself is OK, to confirm that the chunking has not lead to an integrity issue?
