### ISSUE TITLE
SG at THFC-Onondaga has only very sporadic connectivity

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#35]
SG-3115BBBK1C60,40498,Motus/THFC-Onondaga

It connected Aug. 29 after not connecting since July 25.  Connection not resilient enough
to handle rsync of data, so site not updating.  This box also has a bunch of data from
Long Point Crown Marsh (May 31 - June 28) which haven't been fetched yet.

**Comment by StuMackenzie** [comment]
Thanks - data was retrieved, but might have been lost in shuffle. Zoe will visit today and download manually and also try and find a better wifi solution

**Comment by StuMackenzie** [comment]
This station will likely not be online again, so will need to be treated as a regular non-connected site. Good candidate for cellular.
