### ISSUE TITLE
Selva project: register tags 292-302 BI 14.8

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#36]
There are tags with the same IDs registered with BI 10.7, and those above were not named with
augmented IDs, (e.g. 292.1, 292.1, etc), so the registration code failed to process them, and I
didn't notice!

Registrations are in the file /SG/contrib/2016/Selva/TAGS/SELVA.zip

**Comment by jbrzusto** [comment]
Tags are already in motus, so need to have mfgID field changed there:

```sql
update tags set mfgID = mfgID || '.1' where projectID=57 and tagID >= 18540 and tagID <= 18550;
```
as well as changes on sensorgnome.org side

**Comment by denislepage** [comment]
all done
