### ISSUE TITLE
push JamesBay tags to motus

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#44]
149 tags from 2016; **need to know tag model**

**Comment by StuMackenzie** [comment]
This is the best we can do until we get the metadata. All tags/sheets/data are in the field.

Sorry for the delay. REKN tags are NTQB-4-2 with a 5.3 burst rate, all others were NTQB-3-2. I think they have a 6.3 second burst, but the tags were delivered to Allie and I don't have the data sheet for them. It could have been set to  9 seconds...for some reason that rings a bell (wanting longer burst rate).
	Christian

**Comment by jbrzusto** [comment]
Do we have the right project on this?  **JamesBay** tags are:
 - ID#161...ID#310 with BI =10.1
 - except that ID#229 has BI=5.3, and ID#301 is missing

**Comment by StuMackenzie** [comment]
I think so, but I'll check with Friis.

**Comment by jbrzusto** [comment]
long since completed
