### ISSUE TITLE
register BITH 2016 tags

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#48]
somehow missed this email:

> Chris Ward <chrisward27@gmail.com>
> To:    jbrzusto@fastmail.fm
> Subject:    Tag IDs
> Date:    Monday, July 11, 2016 19:08
> Size:    12 KB
> 
> Hi John,
> 
> Here are some tag IDs that need to be put into the MOTUS system. 
> ...
> ​

**Comment by jbrzusto** [comment]
6 tags; what is the tag model.
140-142, 146-148, BI 4.7

**Comment by StuMackenzie** [comment]
NTQB-3-2

**Comment by jbrzusto** [comment]
done.
