### ISSUE TITLE
Register QC-SESA and QC_REKN 2016 with motus

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#51]
This needs: 
 - [x] tag models
 - [x] motus project #s  (just use Aubry - 15 ?)

**Comment by StuMackenzie** [comment]
If registration separated by species:

In 2015: SESA: NTQB-2; REKN NTQB-4-2
In 2016: SESA: NTQB-2;  REKN NTQB4-2

Project #15 Aubry is fine.

**Comment by jbrzusto** [comment]
- [x] 2016: QC-REKN: 148 tags
- [x] 2016:  QC-SESA: 60 tags
- [x] 2015: 169 tags already registered
