### ISSUE TITLE
Register - Tag#74 - 71. Lake Erie Bats

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#54]
New Tag
MotusData/Project 71 Registration

**Comment by jbrzusto** [comment]
do we have a recording or BI for this one?

**Comment by StuMackenzie** [comment]
Google Drive\Motus Data\Unprocessed October 3\Project 71 - Registration

**Comment by jbrzusto** [comment]
apparently that is motus tagID 23272
