### ISSUE TITLE
Please add Yves Turcotte to view Yves Aubry data

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#58]
yturcotte
https://sensorgnome.org/User:Quebec/ 

add permission to access

https://sensorgnome.org/User:yves/

**Comment by jbrzusto** [comment]
Done.

On Wed, Sep 28, 2016, at 10:47, SMackenzie wrote:
> yturcotte
> https://sensorgnome.org/User:Quebec/ 
> 
> add permission to access
> 
> https://sensorgnome.org/User:yves/ 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jbrzusto/TO_DO/issues/58


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada
