### ISSUE TITLE
need motus project for TaylorOdes

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/TO_DO#6]
There are 10 tags registered with sensorgnome.org for this project in 2016, but
no motus project code has been assigned.

**Comment by StuMackenzie** [comment]
Project 99. Atlantic Darners. I don't remember creating this myself, but there are 16 tags there. Perhaps you guys already figured this out.

**Comment by jbrzusto** [comment]
Confirmed by Dom; registrations pushed to motus.
