### ISSUE TITLE
Assign new user for LA stations and process Wisner data

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#60]
I'm pretty sure this was all sorted and is in your que, but just in case. 

Upon review of the user table, I don't think any of the LA stations are officially assigned to anyone. Probably best to create a user for Michael Seymour and Curtis Walker for these sites for now.

For now I think we only have data from Grand Isle, LA and this one.

mseymourDESPAM@wlf.la.gov
cdwalkeDESPAM@g.clemson.edu

Thanks

Stu

**Comment by jbrzusto** [comment]
closing - obsolete.
