### ISSUE TITLE
Duplicate registrations in Mitchell (92. Ontario Barn and Cliff) to 25. Obrien

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#61]
Tags will have to stay in both projects - they'll be separated by deployment dates.

Mitchell/Project 92.
ID 20885 - Tag 439 - put out 7/16 recovered 7/25
ID 20890 - Tag 444 - put out 7/16 recovered 7/25 
ID 20894 - Tag 448 - put out 7/16 recovered 7/25 

to 25. obrien. - deployments in October

I assume we can duplicate registrations on our end as well. 

Stu

**Comment by denislepage** [comment]
Typically, so far, if this would require registering again to the second project, but Catherine to work on a SQL PROC

**Comment by cjardine-bsc** [comment]
Complete
