### ISSUE TITLE
Register QC thrush tags with Motus

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#62]
Can't find any 2016 thrush tags for aubry/desrochers/tremblay - intended Motus project would have been 49.
I'll try and get a list of tags.

Possibly wrapped up in QC - SESA and QC-REKN push?

Thanks

Stu

**Comment by jbrzusto** [comment]
Tag model?
There are 89 tags waiting to be pushed.

**Comment by StuMackenzie** [comment]
NTQB 4-2

**Comment by jbrzusto** [comment]
done

**Comment by StuMackenzie** [comment]
And ID23 was NTQB-3-2

Also got this message from junior - not sure if they're referring to an old tag?

**Comment by jbrzusto** [comment]
I don't know what tag this is.

**Comment by StuMackenzie** [comment]
I think we've dealt with it - may have just been a reminder. Tags from Tremblay et al. Last correspondence was that they hadn't been pushed to Motus yet, but they appear to all be in place now.

 

Thanks

 

S

**Comment by jbrzusto** [comment]
done.
