### ISSUE TITLE
Register Tag #47 - Project 119.

### ISSUE THREAD

**Issue by StuMackenzie** [jbrzusto/TO_DO#64]
\Google Drive\Motus Data\Unprocessed October 3

**Comment by jbrzusto** [comment]
can you take 

https://sensorgnome.org/Sending_Data_for_Automatic_Processing/Sending_Data_for_Automatic_Processing_from_Google_Drive

for a test drive?

**Comment by jbrzusto** [comment]
Done: tag 22115.  Needs model info etc.
