### ISSUE TITLE
James Bay missing tag registration

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#79]
There should be a tag 202, burst rate 5.3, model NTQB-4-2 registered in project 58. James Bay Shorebirds.  It was sent as a replacement tag directly to the tagging site so Allie isn't sure it was registered properly

**Comment by jbrzusto** [comment]
Done, with motus tag ID=23289, **except project ID is wrong**.   I used 58, but James Bay Shorebirds is 38, so this tag might now need to be moved.

**Comment by zcrysler** [comment]
Thanks, sorry for the wrong project number, I moved it over to the right project
