### ISSUE TITLE
JamesBay duplicate tags

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#80]
There was a mix-up with lotek that resulted in 8 pairs of duplicate tags deployed in James Bay for IDs 202, 229, 56, 259, 263, 272, 282, 301, all burst rate 5.3, model NTQB-4-2.  For past reasons some of these are listed as regular IDs and some are .1 IDs.  This is what's in the database right now:

tagID  Motus tag ID	model	        period	deployed?
202	  23289	        NTQB-4-2	5.3	        N
229	  22694	        NTQB-3-2	5.3	        N
256	  missing	 	 	 
259	  missing	 	 	 
263	  missing	 	 	 
272	  missing	 	 	 
282	  missing	 	 	 
301	  22905	        NTQB-4-2	5.3	         N
 	 	 	 	 
tagID with .1	Motus tag ID	model	 	period deployed? 
202.1	        missing	 	 	 
229.1	        22824	        NTQB-4-2	5.3	   Y
256.1	        22851	        NTQB-4-2	5.3	   Y
259.1	        22854	        NTQB-4-2	5.3	   Y
263.1	        22858	        NTQB-4-2	5.3	   Y
272.1	        22867	        NTQB-4-2	5.3	   Y
282.1	        22878	        NTQB-4-2	5.3	   Y
301.1	        missing	 	 	 

Could you add a duplicate record for the "missing" tagIDs? So we need tagIDs 256, 259, 263, 272, 282, 202.1, 301.1, which will be identical to their counterpart.

Some of the data might be use-able since they were deployed in different areas/times, but to keep all the metadata online we need the duplicate tags added to the project.

**Comment by jbrzusto** [comment]
Done.  The set of tags discussed is now:

tagID | Motus tag ID | model | period | deployed?
---|---|---|---|---
202| 23289| NTQB-4-2| 5.3| N
229| 22694| NTQB-3-2| 5.3| N
256| 23313|NTQB-4-2|5.3|N
259| 23314|NTQB-4-2|5.3|N
263| 23315|NTQB-4-2|5.3|N
272| 23316|NTQB-4-2|5.3|N
282| 23317|NTQB-4-2|5.3|N
301| 22905| NTQB-4-2| 5.3| N
202.1|23318|NTQB-4-2|5.3|N
229.1|22824| NTQB-4-2|5.3|Y
256.1|22851| NTQB-4-2|5.3|Y
259.1|22854| NTQB-4-2|5.3|Y
263.1|22858| NTQB-4-2|5.3|Y
272.1|22867| NTQB-4-2|5.3|Y
282.1|22878| NTQB-4-2|5.3|Y
301.1|23319|NTQB-4-2|5.3|N
