### ISSUE TITLE
Data upload page not working

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#83]
There seems to be a problem with the data upload page - when I login all I see is the regular header on top "Motus Data Upload" and then just a blank page underneath.  

Simon Duval is trying to upload a few days of data for the McGill Bird Observatory, they're starting some tag testing there and want to ensure the receiver is running ok before proceeding, it has been having issues lately.

**Comment by jbrzusto** [comment]
this is a continuation of the problem here:

   MotusWTS/Motus-TO-DO#4

I'm giving Paul another heads-up about it.
