### ISSUE TITLE
Project 103 tag registration

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#87]
User tried to upload tag registration files for project 103 and 19/20 went through.  She tried to upload the last one by itself and it still didn't go through, I also tried sending it in.  The log shows that it's been done but "Registered 0 tags with motus".  Is it an issue with the registration or possibly a duplicate?

The file is attached
[103_tag_registrations.zip](https://github.com/jbrzusto/TO_DO/files/1002607/103_tag_registrations.zip)

**Comment by jbrzusto** [comment]
duplicated by #91, which is now closed
