### ISSUE TITLE
Prject 47 failed tag registration

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#89]
I uploaded a batch of tags for project 47 on May 24, all of them went through except tag 149 burst rate 5.898 which has been deployed.  Error message was "Unable to get a good estimate of burst interval", it was deployed closest to receiver SG-3214BBBK1004

**Comment by zcrysler** [comment]
Same issue as above but also with tags 322, 346, 353 burst rate 19.89 in project 47 - didn't upload properly because there wasn't a good estimation of burst interval. Tag 254 also had a warning that there were only 2 bursts detected so the registration may not be accurate.

These tags have already been deployed, the tower closest to the deployment location was Reeds Beach, receiver SG-3214BBBK1004, motus receiver ID 1315​

**Comment by jbrzusto** [comment]
The relevant uncorrected registration errors obtained by editing:
```sql
sqlite> select t1.id, json_extract(t1.data, "$.summary"), json_extract(t1.data, "$.log") 
 from jobs as t1 join jobs as t2 on t1.id=t2.stump 
 where t2.type="registerTags"  and t1.data glob "*under project 47*" 
 order by t1.id desc limit 10;
```
are:
```
Unable to get a good estimate of burst interval for tag id 149 in file tag149.wav
Please re-record this tag and re-upload
Unable to get a good estimate of burst interval for tag id 322 in file tag322.wav
Please re-record this tag and re-upload
Unable to get a good estimate of burst interval for tag id 346 in file tag346.wav
Please re-record this tag and re-upload
Unable to get a good estimate of burst interval for tag id 353 in file tag353.wav
Please re-record this tag and re-upload
Warning: only 2 bursts detected for tag 354 so I can't estimate burst interval error.
This registration might not be accurate.
```
For 2017-04-18 to 2017-05-22, this receiver's detections of bare tag IDs in the set 
149, 322, 346, 353, 354 (**N.B.: not 254**)
look like this:
```
      n       bi        bi.sd
322 131 19.89507 0.0001163828
346 259 19.89478 0.0477221765
353 251 19.89489 0.0321426428
354  64 19.89500 0.0001943776
```
so based on this, I'm requesting the period for tag 354 be corrected, and registering the remaining 3 tags with nominal BI=19.895

So far, there's no sign of tag 149 on that receiver.

**Comment by jbrzusto** [comment]
Looking at the recording for tag 149 more carefully, there are 4 good bursts, so I'm not sure
why the automatic algorithm failed.
So I'm registering this one with BI=5.898.
