### ISSUE TITLE
confirmation email update

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#92]
Could we add the link to the hourly plots in the confirmation email when detection data is uploaded?  It's included with the auto email for tag registrations to get the tag file, just something similar to this line:

The on-board database for your recent tags is available here:
   https://sensorgnome.org/download/47

**Comment by jbrzusto** [comment]
Sure - makes sense.
The only reason it wasn't is that the "thanks for the upload" email gets sent as soon as an upload
starts processing, while the location of the downloads didn't used to be known until files had been
processed.  But now that users are supposed to assign uploads to a project, I'll just include the link
to that project's download area.

**Comment by zcrysler** [comment]
Right, I guess the only time that wouldn't work is if they haven't registered the receiver in the database yet, because then I think it gets sent to project 0 even if they assign project at time of upload, unless I'm mistaken?

**Comment by jbrzusto** [comment]
I was wrong - that email is now only sent when processing is complete anyway.

Here's what I'm thinking:
- the email will include each URL, sparing the user from searching for relevant files in a large
listing
### Implementation: ###
- the full URL to each file generated or changed by  should be added to the uploadJob's 
json data field as "$.products", a character vector
- handleUploadProcessed should grab the topJob's "products" field and include it in the email.
- new functions:  jobProduced(j, u) either adds URL u to the products field, or (if u is missing) returns
the product field as a character vector

**Comment by jbrzusto** [comment]
Hmm. I'm wrong again, the email is being sent right after the upload.
Looking into this too...
