### ISSUE TITLE
Identical tag registrations - project 78

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#94]
Hannah MacKellar has uploaded tag 165 a few times with different recordings, it keeps coming up with the following error:

Tag id 165 not found in file tag165.wav, however, that file had 3 detections of id 163
   Perhaps the recording or the tag is mis-labelled?

She's certain she's recording the tag labelled as 165 - is it truly identical to 163?  If so I'll tell her to send it back to Lotek

**Comment by jbrzusto** [comment]
That's a programming error by Lotek.  I ran the tag finder on tag163.wav
and tag165.wav from the first batch uploaded on June 2, and they both
show only ID 163, and with the same burst interval.  So unfortunately,
that tag "165" is identical to the tag actually labelled "163" in the same
batch.  The results from the repeated recordings just confirm that.
