### ISSUE TITLE
data upload site issue

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#98]
When I log into https://sensorgnome.org/upload/index.php, I just get the "Motus Data Upload" banner with a blank page underneath, screenshot attached

<img width="963" alt="screen shot 2017-06-12 at 1 34 43 pm" src="https://user-images.githubusercontent.com/22080197/27054008-44c8de1c-4f74-11e7-9aa9-cdbebcfe067d.png">

**Comment by jbrzusto** [comment]
Closing in deference to https://github.com/MotusWTS/Motus-TO-DO/issues/25
